### ISSUE TITLE
Deep SORT error!

### ISSUE THREAD

**Issue by HadiDecentraTech** [cong/yolov5_deepsort_tensorrt#13]
![err](https://user-images.githubusercontent.com/95681307/159508399-a3f605b0-e237-41aa-88d1-468b8c3147dc.png)
Hello guys, I am facing this error please help me solve it, it seems that this error is caused by deep sort because the yolov5 engine doesn't give any errors and I can detect with yolov5.engine but the tracker give this error.

Those are the versions of the packages installed on my ubuntu 18 device:
![vers](https://user-images.githubusercontent.com/95681307/159509944-50b5d8b3-20f1-49fe-90ad-f9a4fcdf3b93.png)

**Comment by cong** [comment]
Hi, there, according to the error message _PyCUDA ERROR_, you can use `Context.pop()` to cleanup the context stack.

**Comment by hicsuntleones** [comment]
Hi, I used the code as it is on a Jetson Xavier AGX with all dependencies installed and 
I get the same error at the end, but the pre-conditions look different. It seems to be a serialization error.
![deepsorterror](https://user-images.githubusercontent.com/1890690/200122301-55d91899-d4c7-424a-93fa-cf6f93a90404.png)

Do you have any suggestion to fix it?

Thanks

**Comment by cong** [comment]
> Hi, I used the code as it is on a Jetson Xavier AGX with all dependencies installed and I get the same error at the end, but the pre-conditions look different. It seems to be a serialization error. ![deepsorterror](https://user-images.githubusercontent.com/1890690/200122301-55d91899-d4c7-424a-93fa-cf6f93a90404.png)
> 
> Do you have any suggestion to fix it?
> 
> Thanks

**1. Please check if there is any problem with the installation of tensorrt.
2. Please check if there is any problem with the generated engine file.**

**Comment by hicsuntleones** [comment]
1. No problem with Tensort.
2. I am using the engine file that come with your original repo. I though it was good for the demo. Should I generate one for the Xavier?

**Comment by cong** [comment]
> 1. No problem with Tensort.
> 2. I am using the engine file that come with your original repo. I though it was good for the demo. Should I generate one for the Xavier?

Sorry about reply you so late. 
Yeap, you should generate one for the Xavier.
