### ISSUE TITLE
您好，我的环境是NVIDIA® Jetson Xavier NX，速度很慢，帧率2左右，请问是什么原因？

### ISSUE THREAD

**Issue by Rehan-DL** [cong/yolov5_deepsort_tensorrt#22]

**Comment by cong** [comment]
能详细的说明下情况么，依赖的版本，GPU占用情况，等等

**Comment by Rehan-DL** [comment]
Ubuntu 18.04
NVIDIA driver 470.94
CUDA 10.2
TensorRT 7.0.0.11

cpu:65%~90%
Mem:90%
Swp:50%
EMC:15%左右
GPU:通常是2%，时不时会跳到85%

**Comment by cong** [comment]
GPU利用率2%，不高，GPU占用显存多少？建议再排查排查搭建的环境。
