### ISSUE TITLE
pycuda._driver.LogicError: cuDeviceGet failed: initialization error

### ISSUE THREAD

**Issue by oussamabousselmi** [cong/yolov5_deepsort_tensorrt#3]
when i run demo_trt.py i got this error 
    detector = Detector(engine_file_path)
  File "/home/radar/Desktop/yolotrt/yolov5_deepsort_tensorrt/detector_trt.py", line 43, in __init__
    self.cfx = cuda.Device(0).make_context()
pycuda._driver.LogicError: cuDeviceGet failed: initialization error

**Comment by cong** [comment]
Please carefully check whether the type and dimension information of the input data is correct.

**Comment by lencm** [comment]
This problem can occur with the engine file provided by the author, and can be solved using your own engine file.
