### ISSUE TITLE
libmyplugins.so在哪？

### ISSUE THREAD

**Issue by gewenpulan** [cong/yolov5_deepsort_tensorrt#4]
作者，您好，我就是单纯测试一下效果，libmyplugins.so这个文件从哪里找？

**Comment by lvxuanxuan123** [comment]
> 已上传

请问这个文件是怎么生成的

**Comment by cong** [comment]
> > 已上传
> 
> 请问这个文件是怎么生成的

在生成 yolov5.engine 的时候会相应生成这个文件
