### ISSUE TITLE
模型运行时所占的内存怎么看？

### ISSUE THREAD

**Issue by ZhangChaoZhong** [cong/yolov5_deepsort_tensorrt#7]
![图片](https://user-images.githubusercontent.com/30583522/142805171-47cf4b88-a34e-4683-babc-7cf187c52cc2.png)
您好，请问下模型运行时所占的内存怎么算出来的？跟模型的权重一样吗？

**Comment by cong** [comment]
您好，我是直接通过终端命令查看的GPU占用显存情况
