### ISSUE TITLE
请问这个移植到板子上的也是有跟踪效果的吗

### ISSUE THREAD

**Issue by Gakkifan1314** [cong/yolov5_deepsort_tensorrt#9]
作者您好，我想问一下这个yolov5+deepsort的模型在转换完.engine之后在在板子上跑也是有跟踪效果的吗？

**Comment by cong** [comment]
> 作者您好，我想问一下这个yolov5+deepsort的模型在转换完.engine之后在在板子上跑也是有跟踪效果的吗？

您好！是的，在板子上运行的效果是一样的，只是板子资源有限且架构不同会有一定的时效性、适配性影响。

**Comment by Gakkifan1314** [comment]
> 

您好！我想再问题下如果不在tx2上使用python转而使用C++实现deepsort应该使用什么方法呢？就是在板子上使用python之类库那些。就是有没有yolov5+deepsort移植在板子上是C++的那种？

**Comment by cong** [comment]
> 

您好，在https://github.com/cong/yolov5_deepsort_tensorrt_cpp这个repo中提供了在x86平台下的测试用例，暂时还没有提供在板子上的测试用例。
